apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tguillaume-application
  namespace: tguillaume
spec:
  destination:
    namespace: tguillaume
    server: https://kubernetes.default.svc
  project: tguillaume
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helmchart
    repoURL: https://github.com/Guithi0777/Metadata.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
