apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tguillaume-appproject
  namespace: tguillaume
spec:
  description: demo d'une application geree as code
  destinations:
  - name: in-cluster
    namespace: tguillaume
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/O-clock-Hati/demo-argo-app.git
status: {}
