

---

on: [push]

jobs:
  bump-version:
    name: testaction
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node20
        uses: actions/setup-node@v4
        with:
         node-version: 20
      - uses: ./
        with:
          person: 'Boris'
