

---

on: [push]

jobs:
  bump-version:
    name: testaction
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: testaction
        id: testaction
        uses: guithi0777/testaction@v2
        with:
          version-type: major

      - name: Get the New Version
        run: echo "New version is ${{ steps.testaction.outputs.new-version }}"
