---

name: My Workflow

on:
  workflow_dispatch:
    
jobs:

  Chouette:
    runs-on: ubuntu-latest
    environment:
      name: Checkout repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  composite_action_job:
    runs-on: ubuntu-latest
    name: My composite action use
    steps:
    - name: First composite action step
      id: mycompositeaction
      uses:
        DevOps/CustomActions/mycompositeaction@v1
      with:
        your-name: 'Pushpa'
