---

name: My Workflow

on:
  workflow_dispatch:
    
jobs:

  Checkout:
    runs-on: ubuntu-latest
    
    environment:
      name: Checkout repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  composite_action_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: Checkout
    name: My composite action use
    steps:
    - name: First composite action step
      id: mycompositeaction
      uses: guithi0777/actions.yml@v1
      with:
        your-name: 'Pushpa'
